# Generated by Django 3.2.23 on 2023-12-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0147_alter_profile_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='plagiarism_points',
            field=models.FloatField(default=None, null=True, verbose_name='plagiarism_points'),
        ),
    ]
