# Generated by Django 3.2.23 on 2023-12-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0148_submission_plagiarism_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='plagiarism_points',
            field=models.FloatField(default=0, null=True, verbose_name='plagiarism_points'),
        ),
    ]
