# Generated by Django 3.2.23 on 2023-12-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0149_alter_submission_plagiarism_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='plagiarism_points',
            field=models.FloatField(default=0, null=True, verbose_name='plagiarism points'),
        ),
    ]
