# Generated by Django 3.2.23 on 2023-12-25 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0150_alter_submission_plagiarism_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='plagiarism_points',
        ),
    ]
